apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-payment-service
  labels:
    app: payment-service
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: payment-service
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
