replicaCount: 2

image:
  repository: ghcr.io/lucasgeek/payment-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8081
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

env:
  POSTGRES_USER: payments
  POSTGRES_PASSWORD: ""
  JWT_SECRET: ""

config:
  springDatasourceUrl: "jdbc:postgresql://postgres:5432/payments"
  kafkaBootstrapServers: "kafka:9092"
  redisHost: "redis"
  redisPort: "6379"
