apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-notification-service-config
  labels:
    app: notification-service
    release: {{ .Release.Name }}
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
